dist: trusty
sudo: required

language: generic
compiler:
- gcc
- clang

matrix:
  include:
  - compiler: gcc
    before_install:
      - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      - sudo apt-get update -qq

    install:
      # install compiler and standard library
      - sudo apt-get install -qq g++-5
      - sudo apt-get install -qq libstdc++6
      - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 50

      # install build tools
      - sudo apt-get install -qq make

      # install libraries
      - sudo apt-get install -qq libpthread-stubs0-dev
      - sudo apt-get install -qq libboost-dev
      - sudo apt-get install -qq libboost-system-dev
    before_script: 
      - g++ --version

  exclude:
  - compiler: clang

# command to run tests
script: 
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov

