version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run: docker build -t daviduser/cpp-simple-socket
      - run: docker run --rm daviduser/cpp-simple-socket
